# Generated by Django 3.2.16 on 2023-03-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователя', 'verbose_name_plural': 'пользователи'},
        ),
    ]
