# Generated by Django 3.2 on 2023-03-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230323_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Связь произведения и жанра', 'verbose_name_plural': 'Связи произведений и жанров'},
        ),
    ]
